ALTER TABLE natural_person ADD COLUMN IF NOT EXISTS zip_code VARCHAR(20);
ALTER TABLE natural_person ADD COLUMN IF NOT EXISTS number VARCHAR(20);
ALTER TABLE natural_person ADD COLUMN IF NOT EXISTS complement VARCHAR(100);
ALTER TABLE natural_person ADD COLUMN IF NOT EXISTS neighborhood VARCHAR(100);
ALTER TABLE natural_person ADD COLUMN IF NOT EXISTS city VARCHAR(100);
ALTER TABLE natural_person ADD COLUMN IF NOT EXISTS state VARCHAR(50);
